config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :home, only: 'index' do
    get 'admin', on: :collection
  end

  resources :bookings do
    get 'reserve_seats', on: :collection
    get 'make_booking', on: :collection
    get 'reports', on: :collection
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  include ImageUploader::Attachment(:image)
  has_many :show_times
  has_many :screens, through: :show_times
  has_many :slots, through: :show_times
  has_many :movie_dates, through: :show_times


  default_scope ->{ where(active: true) }
end

app/models/movie_date.rb
class MovieDate < ApplicationRecord
  has_many :show_times
  has_many :screens, through: :show_times
  has_many :movies, through: :show_times
  has_many :slots, through: :show_times
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :seat
  belongs_to :show_time
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_one :user
end

app/models/screen.rb
class Screen < ApplicationRecord
  has_many :show_times
  has_many :movies, through: :show_times
  has_many :slots, through: :show_times
  has_many :movie_dates, through: :show_times
  has_many :screens_seats
  has_many :seats, through: :screens_seats
end

app/models/screens_seat.rb
class ScreensSeat < ApplicationRecord
  belongs_to :seat
  belongs_to :screen
end

app/models/seat.rb
class Seat < ApplicationRecord
  has_many :screens_seats
  has_many :screens, through: :screens_seats
end

app/models/show_time.rb
class ShowTime < ApplicationRecord
  belongs_to :movie
  belongs_to :slot
  belongs_to :screen
  belongs_to :movie_date
end

app/models/slot.rb
class Slot < ApplicationRecord
  has_many :show_times
  has_many :screens, through: :show_times
  has_many :movies, through: :show_times
  has_many :movie_dates, through: :show_times
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role
  has_many :reservations

  before_validation :set_role


  def set_role
    self.role = Role.find_by(name: "customer") unless self.role
  end

  def admin?
    role && role.name == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def reserve_seats
    screen = Screen.find(params[:screen_id])
    @screen_seats = screen.screens_seats
    @show_time = ShowTime.find_by(screen_id: params[:screen_id], slot_id: params[:slot_id], movie_date_id: params[:movie_date_id], movie_id: params[:movie_id])
    @reserved_seats = Reservation.where(show_time_id: @show_time.id).pluck(:seat_id)
  end

  def make_booking
    @show_time = ShowTime.find(params[:show_time_id])
    @seat_numbers = params[:seat_numbers].join(",")
    params[:seat_numbers].each do |seat_number|
      seat = Seat.find(seat_number)
      Reservation.create!(show_time_id: params[:show_time_id], seat_id: seat.id, user_id: current_user.id)
    end
  end

  def reports
    reservations = Reservation.joins(show_time: :movie_date).where("movie_dates.date = ?", params[:booking_date])
    send_data Report.new(reservations).perform, filename: "reports-#{Date.today}.csv"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    redirect_to admin_home_index_path if current_user.admin?
    @movies = Movie.includes(show_times: [:movie, :slot, :screen, :movie_date])
  end

  def admin
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def set_available_class(seat_id)
    @reserved_seats.present? && @reserved_seats.include?(seat_id) ? { class: "reserved", disabled: true } : { class: "available" }
  end
end

app/views/bookings/make_booking.html.slim
.container
  .row.mt-5
    .col-12
      p = "Greetings! Your Booking has been made for movie for #{@show_time.movie.name} in #{@show_time.screen.name} on #{@show_time.movie_date.date.strftime('%d-%m-%Y')} at #{@show_time.slot.time} and your seat numbers are #{@seat_numbers}"

app/views/bookings/reserve_seats.html.slim
.container.mt-5
  = form_tag make_booking_bookings_path, method: :get do
    = hidden_field_tag "show_time_id", @show_time.id
    .row
      - @screen_seats.each do |screen_seat|
        .col-4.mb-4
          label class="checkbox"
            = label_tag "#{screen_seat.seat.number}, (#{screen_seat.price})"
            = check_box_tag "seat_numbers[]", screen_seat.seat.id, false, set_available_class(screen_seat.seat.id)
      = submit_tag "Book Now", class: 'book_tickets', disabled: true


javascript:
  $('.reserved').click(function (){
    $(this).css('background-color', 'red')
  })

  $('.available').click(function () {
    $('.book_tickets').removeAttr("disabled");
  })

app/views/home/admin.html.slim
.container.mt-5
  .row
    .col-12
      p Dowload the reports here:
      = form_tag reports_bookings_path, method: :get
        = label_tag "booking_date", "Booking Date", class: 'col-left control-label'
        | &nbsp;
        = date_field_tag("booking_date", "", class: 'inline-block')
        br
        br
        = submit_tag "Show Report", id: 'show_report'

app/views/home/index.html.slim
.container.mt-5
  .row
    - @movies.each do |movie|
      .col-4.mb-4
        = form_tag reserve_seats_bookings_path, method: :get
          .row.justify-content-center
            = image_tag movie.image_url, size: "10x300"
          .row.justify-content-center
            = movie.name
            = hidden_field_tag "movie_id[]", movie.id
          .row.justify-content-center
            = movie.description
          .row
            - movie.screens.group(:id).each do |screen|
              .col-6
                = radio_button_tag "screen_id", screen.id
                | &nbsp;
                = label_tag screen.name
            .col-6
              = select_tag "movie_date_id", options_for_select(movie.movie_dates.group(:id).collect { |movie_date| [movie_date.date.strftime("%d %m %y"), movie_date.id] })
            .col-6
              = select_tag "slot_id", options_for_select(movie.slots.group(:id).collect{|slot| [slot.time, slot.id]})
          br
          = submit_tag "Book Now"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag  'application' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  button.navbar-toggler aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo03" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  a.navbar-brand.ml-13 href="/"  Home
  #navbarTogglerDemo03.collapse.navbar-collapse.justify-content-center
    span Welcome to our Movie Booking Application
    - if current_user
      span.user-display = "Welcome #{current_user.email}"
      | &nbsp;
      span = link_to "Sign Out", destroy_user_session_path